# Generated by Django 2.2.28 on 2025-03-15 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('card_front', models.TextField()),
                ('card_back', models.TextField()),
                ('confidence_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('topic_name', models.CharField(max_length=128)),
                ('learning_score', models.IntegerField(default=0)),
                ('study_next', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='revizo.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='revizo.UserProfile'),
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('explain_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ai_explanation', models.TextField()),
                ('ai_explanation_date', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='revizo.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='revizo.Topic'),
        ),
    ]
