# Generated by Django 3.2.25 on 2025-03-24 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revizo', '0003_auto_20250322_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='confidence_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='explanation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='learning_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='study_next',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
