# Generated by Django 3.2.25 on 2025-03-25 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revizo', '0004_auto_20250324_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_name', 'user')},
        ),
    ]
