# Generated by Django 3.2.25 on 2025-03-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revizo', '0005_auto_20250325_2250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
    ]
