# Generated by Django 3.2.25 on 2025-03-26 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revizo', '0007_remove_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
