# Generated by Django 3.2.25 on 2025-03-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revizo', '0008_remove_userprofile_website'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('topic_name', 'subject')},
        ),
    ]
